version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
